gmail:
  applicationName: pdf-parser
  tokensDirectoryPath: tokens
  credentialsFilePath: /credentials.json
  userId: example@gmail.com

firebase:
  storage:
    googleApplicationCredentials: /serviceAccountKey.json
    storageBucket: project_id.appspot.com
