gmail:
  applicationName: pdf-parser
  tokensDirectoryPath: tokens
  credentialsFilePath: /gmail-credentials.json
  userId: example@gmail.com

firebase:
  storage:
    googleApplicationCredentials: /firebase-credentials.json
    storageBucket: project_id.appspot.com
